### ISSUE TITLE
Cop suggestion: Check for testing of private methods

### ISSUE THREAD

**Issue by andyw8** [backus/rubocop-rspec#175]
If the spec follows the standard convention of `describe "#foo"` then it should be fairly easy to verify that `#foo` is a public method.

**Comment by dgollahon** [comment]
> it should be fairly easy to verify that #foo is a public method.

@andyw8: Do you have any idea for doing this? I don't see how we could easily do this given that rubocop just works on the AST. Unless you have a strategy in mind I'm not aware of, I think we should close this and perhaps leave it to a tool that does dynamic analysis.

**Comment by backus** [comment]
Probably would just look for expects with `__send__`, and `send` I imagine

**Comment by dgollahon** [comment]
@backus: Ahhh, yeah, that's a good point, we could do that.

**Comment by andyw8** [comment]
To be be honest I can't remember the situation I had encountered when I suggested this cop.

Feel free to close, it's probably not hugely valuable.

**Comment by dgollahon** [comment]
@andyw8: Sounds good :)
