### ISSUE TITLE
Generate a blacklist when installing

### ISSUE THREAD

**Issue by jcoyne** [backus/rubocop-rspec#192]
How about making a .rubocop-rspec configuration that can be generated that has an explicit list of the checks that should be run.  Then updating the rubocop-rspec gem would not automatically add more checks into the build. This way, so long as I have a working configuration, the version of rubocop-rspec will not affect the outcome of the tests that are run.   This will be helpful for people who don't want to spend time fixing the build every time new cops are added.

**Comment by backus** [comment]
Have you used `--auto-gen-config`? It will adjust the cop settings given what style it detects you use. If it finds a bunch of violations it will just disable the cop for you.

**Comment by jcoyne** [comment]
Yes, but won't that overwrite my existing config, that I've tuned by hand?

**Comment by backus** [comment]
No it generates a `.rubocop_todo.yml` file which your config can then inherit from. The idea is that you manually groom `.rubocop.yml` and let the `.rubocop_todo.yml` be an automated dump

**Comment by backus** [comment]
@jcoyne did `--auto-gen-config` address most of your concern? If it didn't I'd recommend upstreaming this idea to rubocop. There isn't much this gem can do beyond just adding cops.

**Comment by backus** [comment]
Ping @jcoyne ^

**Comment by jcoyne** [comment]
¯\_(ツ)_/¯ I see your point that it needs to happen in rubocop. But the pain is caused by rubocop-rspec injecting new rules ever month or so.

**Comment by bquorning** [comment]
I believe the `DisabledByDefault` was intended to solve this problem: https://github.com/bbatsov/rubocop/blob/v0.42.0/config/default.yml#L50-L56

**Comment by backus** [comment]
Sounds like a perfect fix for @jcoyne.
