### ISSUE TITLE
Enforce either `it { should ... }` OR `it { is_expected.to }`

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#194]

**Comment by andyw8** [comment]
Should it default to `is_expected`? `should` seems like a legacy of the older syntax.

**Comment by backus** [comment]
Heh yeah I was just having this conversation. My understanding is that `is_expected` is supposed to be better than `should` but I don't understand why besides 1) the authors say its better and 2) it is simply an alias for `expect(subject)` while `should` has more indirection. Do you know any other reasons?

**Comment by backus** [comment]
@andyw8 Heh yeah I was just having this conversation. My understanding is that `is_expected` is supposed to be better than `should` but I don't understand why besides 1) the authors say its better and 2) it is simply an alias for `expect(subject)` while `should` has more indirection. Do you know any other reasons?

**Comment by backus** [comment]
(Regardless of my preference I would definitely make `is_expectedd` the default since that is what the RSpec team recommends)

**Comment by andyw8** [comment]
I would say it's just more congruent with the newer syntax, no strong technical reason.
