### ISSUE TITLE
RSpec/ExpectActual false positive against routing specs?

### ISSUE THREAD

**Issue by DMA57361** [backus/rubocop-rspec#198]
One of our apps has a number of routings specs, that do things like the following (in line with https://www.relishapp.com/rspec/rspec-rails/docs/routing-specs):

```
expect(get: "/some/path").to_not be_routable
expect(get:"/another/path").to route_to(...)
```

The RSpec/ExpectActual cop reports these as offences and I suspect it probably shouldn't:

```
spec/routing/some_spec.rb:6:12: C: RSpec/ExpectActual: Provide the actual you are testing to expect(...)
    expect(get: "/some/path").to route_to(
           ^^^^^^^^^^^^^^^^^
```

For now I've just configured this cop to exclude `spec/routing/**/*`

**Comment by backus** [comment]
I'm sorry about this. I need to figure out what our "rails policy" is. I'll try to followup soon

**Comment by taryneast** [comment]
These specs can occur in files other than `spec/routing/**/*`...
I don't know if it's possible to switch off a cop if the spec is marked as `:type => :routing`, but that would be cool if it is :)

**Comment by backus** [comment]
Out of curiosity what directories are the false positives in for you @taryneast?

**Comment by backus** [comment]
> I don't know if it's possible to switch off a cop if the spec is marked as `:type => :routing`, but that would be cool if it is :)

I think a more practical option would probably just be to add some code for special casing this. I think I'm fine with this.

**Comment by backus** [comment]
I've implemented a fix (just added an exclude to the config file) in #332
