### ISSUE TITLE
Cop idea: Don't use match_array and contain_exactly with 1-element arrays

### ISSUE THREAD

**Issue by bquorning** [backus/rubocop-rspec#209]
I’ve never really understood why you’d use `match_array` or `contain_exactly` on 1-element arrays. E.g.:

``` rb
expect(foo).to match_array([42])
expect(foo).to contain_exactly(42)
```

I’d propose we write a cop that check against calling `match_array` with a one-element array, and against calling `contains_exactly` with one argument. Calling `contains_exactly` with one _splat_ argument should be fine, though.

Update: My preferred alternative for both examples would be

``` rb
expect(foo).to eq([42])
```

**Comment by andyw8** [comment]
I can think of one counterpoint. If you're writing a set of examples which have a similar structure, and where one expects a single-element array, but others expect multi-element arrays, then you might prefer to stick with consistent matchers across all the examples.
