### ISSUE TITLE
Add `nil` to `BeEql`

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#217]

**Comment by bquorning** [comment]
For matching `nil`, I think we should recomend using `be_nil` over `be(nil)`.

**Comment by backus** [comment]
Well this cop specifically helps improve the semantics of instances where users were already writing things like `eql(false)`. There should certainly be a cop that enforces either `be(nil)` or `be_nil` (I think someone is working on it?) but it shouldn't be this cop
