### ISSUE TITLE
MessageExpectation cop is useless

### ISSUE THREAD

**Issue by dziulius** [backus/rubocop-rspec#218]
`allow` and `expect` have a different purpose (stubbing vs mocking). Why would you enforce to use only one?

**Comment by bquorning** [comment]
There was some discussion on the subject in #23.

**Comment by backus** [comment]
Yeah basically the point is that you should either be doing

```ruby
allow(foo).to receiver(:bar)

test_something

expect(foo).to have_received(:bar).with(baz)
```

OR

```ruby
expect(foo).to receiver(:bar)

test_something
```

which are absolutely two different styles. I currently am using the first style on my main project and this cop works like a charm I do think that it could probably be better calibrated for `expect(...).to receive` style but I don't know exactly what this means yet. 

This is definitely the most misunderstood cop right now. I should probably either improve it or disable it by default. This is now the second inflammatory complaint about it.
