### ISSUE TITLE
Suggested changes to cops

### ISSUE THREAD

**Issue by JonRowe** [backus/rubocop-rspec#228]
As per #221 a list of cops that should be disabled or modified as they don't represent best practises but opinions. Disclaimer, does not represent official RSpec team views, but I feel I probably fall very close inline. Forgive me if any are already disabled by default.

> DescribeClass

Would prefer this disabled or modified, as a constant this means code has to be loaded before the spec (bad for rails specs), it's better to do that loaded after parsing the specs for filtering etc. The preferred practise is `"MyClass"` e.g. a string.

> DescribedClass

Disabled if the above is disabled...

> ImplicitExpect

The default style for this should be to not use it at all, it's a legacy hang around.

> LeadingSubject

Entirely stylistic, nothing wrong with the cop but it's a bad default to be on as it's a personal choice.

> Multiple Expectations

Entirely debatable, as with composable matchers this is soothed a bit, but the intent is one 'business' expectation per spec, not literally. Makes people feel bad without them necessarily doing anything wrong.

**Comment by backus** [comment]
This is great feedback, thank you. I've personally wondered where the rspec team would draw the line.

Of course part of me wonders what options we should explore besides just disabling by default. I think part of the issue here is not being able to properly delineate a best practice cop from a style cop. If we could have nested namespaces like `RSpec/Style/LeadingSubject` that would be nice. 

I didn't get the time I wanted tonight to respond to specific cops mentioned in this issue so I'll try to follow up soon with my thoughts on each recommended change

**Comment by backus** [comment]
Thanks again for the input @JonRowe. Here are my rough thoughts

> cops that should be disabled or modified as they don't represent best practises but opinions

As a general note, I think I want rubocop-rspec to be more than just the style and best practices that the RSpec core team views as universally applicable. RuboCop isn't just about enforcing universal best practices for ruby but also for enforcing a consistent set of practices with reasonable defaults that can be customized. With that said, I think I'm onboard with the spirit of many of your recommendations.

* DescribeClass

I would be open to adding an option for permitting constants specified with strings. We might be able to automatically enable this option if `RailsCops` is enabled.

* DescribedClass

I *think* this cop will not flag constants if the subject of `RSpec.describe` is not a constant. I'd be happy to adjust it if this is not the current behavior. Assuming this is the behavior though I think it is fine to leave enabled.

* ImplicitExpect

Good point. I'd be happy to add another option that just flags all implicit expectations.

* LeadingSubject

I would be fine with disabling this by default.

* Multiple Expectations

I think this is fine to leave enabled. I view it as comparable to `MethodLength`, `BlockLength`, etc. It is a metric that should help you get an upperbound on methods where something fishy is going on. I'd be fine to raise the default to `2` but after that I think this is a useful cop and I would just encourage people to just use `--auto-gen-config` at first and then decide if they want to set a different default.

What do you think? (cc @andyw8 @bquorning)
