### ISSUE TITLE
Question: why enforce expect over allow?

### ISSUE THREAD

**Issue by turboladen** [backus/rubocop-rspec#229]
I was just giving rubocop-rspec a whirl and amongst some other surprises, I don't understand why rubocop-rspec fails for using `expect` over `allow`. Could you explain? These methods have different purposes; I use `expect` when I want to make sure the method is called and `allow` when I don't necessarily want to test to make sure it was called.

I guess after reading the docs [here](https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/message_expectation.rb), I should rephrase: the cop seems to enforce one over the other, but not allow both. How come?

**Comment by bquorning** [comment]
You're not the first to ask this question. In fact, there's an open pull request #224 to change this cop.

**Comment by turboladen** [comment]
Oh, nice! Thanks for the quick response!
