### ISSUE TITLE
Add option for MultipleExpectation to special case aggregate_failures

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#233]
As @JonRowe mentioned in #228, the general guideline is to have "one business rule expectation" per spec. Sometimes this isn't always possible with a single `expect(...)`. It would be nice to support something like

```ruby
aggregate_failures("verifying response") do
  expect(response.status).to eq(200)
  expect(response.headers).to include("Content-Type" => "text/plain")
  expect(response.body).to include("Success")
end
```

being treated as one expectation

**Comment by JonRowe** [comment]
Great way to represent it.

**Comment by Darhazer** [comment]
I think there should be an option for `MaxAggregatedExpectations` as even with `aggregate_failures` 10 expectations might be too much.

Also an option may determine if `RSpec/MultipleExpectation` recommends using `aggregate_failures` when there is more then whatever the maximum expectations are set. With such recommendation, it is possible to implement an autocorrect as well.

**Comment by backus** [comment]
This was implemented in https://github.com/backus/rubocop-rspec/pull/329
