### ISSUE TITLE
Cop idea: Detect receive_message_chain/stub_chain with just one argument

### ISSUE THREAD

**Issue by bquorning** [backus/rubocop-rspec#240]
Sometimes, when code change, I have seen specs change from e.g. `allow(foo).to receive_message_chain(:bar, :baz)` to `allow(foo).to receive_message_chain(:bar)`. Since `receive_message_chain` (and `stub_chain`) [is a code smell](https://github.com/backus/rubocop-rspec/pull/187), we might have a cop that suggests replacing with `allow(foo).to receive(:bar)`.

I know that it clashes a little bit with our MessageChain cop from #187, but I think that it would be useful anyway. Perhaps it could even be part of that cop?

**Comment by backus** [comment]
I would be onboard with this cop
