### ISSUE TITLE
Rails/HttpPositionalArguments autofix doesn't preserve parenthesis

### ISSUE THREAD

**Issue by mockdeep** [backus/rubocop-rspec#251]
We specify our spec actions with parenthesis, but the `Rails/HttpPositionalArguments` autofix doesn't preserve them:

```diff
-    put(:update, valid_params)
+    put :update, params: valid_params
```

**Comment by bquorning** [comment]
That cop is defined by RuboCop proper, not RuboCop/RSpec. I suggest you open an issue at https://github.com/bbatsov/rubocop/issues

**Comment by mockdeep** [comment]
Oh, woops. Ha, I thought I was there.
