### ISSUE TITLE
Cop idea: Detect stubbing in a `before(:all)` hook

### ISSUE THREAD

**Issue by andyw8** [backus/rubocop-rspec#257]
This would be a followup to #252.

Stubbing within a `before(:all)` will only work for the first example in the test. If you only have one example in a spec, it wouldn't matter. If you add a second example that is also dependent on the stubbing, it will pass in isolation but will fail roughly 50%  time when the whole spec file is run (due to RSpec's random ordering).

Proof:
https://gist.github.com/andyw8/7aa312287dd5c60412475a147900e121

**Comment by andyw8** [comment]
https://github.com/rspec/rspec-mocks/#use-beforeexample-not-beforecontext

> Stubs in before(:context) are not supported. The reason is that all stubs and mocks get cleared out after each example, so any stub that is set in before(:context) would work in the first example that happens to run in that group, but not for any others.
>
> Instead of before(:context), use before(:example).

**Comment by andyw8** [comment]
Interestingly, it seems this is only a problem when using Mocha. RSpec already protects against this:

https://relishapp.com/rspec/rspec-mocks/docs/basics/scope#cannot-create-doubles-in-a-`before(:context)`-hook

**Comment by backus** [comment]
Neat. I probably wont implement since rspec correctly guards against this by default and I don't use mocha. Would accept a PR for this though

**Comment by bquorning** [comment]
> Interestingly, it seems this is only a problem when using Mocha. RSpec already protects against this:

I disagree with @backus on this one. I don’t think this is a responsibility of rspec-rubocop.

That said, it would be nice to have a shared repository of one-off cops. I have three custom cops in a lib/rubocop folder that I might as well share, if there was such a place.

**Comment by backus** [comment]
@bquorning I have a handful of cops in a random repository called http://github.com/backus/rubocop-devtools. I'd recommend just casually publishing your own repo. This will be even easier once we have #246

**Comment by andyw8** [comment]
I guess this is quite a niche cop. I like the idea of making it easy for users to have their own repos of custom cops.
