### ISSUE TITLE
Cop Idea: Repeated Description in Same Example Group

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#258]
This issue is very common: https://github.com/bbatsov/rubocop/pull/3816#discussion_r93786647

Basically, it is easy for people to bootstrap tests they write by copying the previous and forgetting to change the description string. We should consider flagging this if the repeated description is not inside a new `context`, `description`, `shared_example`, etc.

**Comment by backus** [comment]
@andyw8 @bquorning @dgollahon what do you think?

**Comment by andyw8** [comment]
I haven't run into this very often, but I see no problem with adding a check for it.

**Comment by dgollahon** [comment]
@backus: I think it's interesting and probably helpful for writing more descriptive tests. I wonder if it should be enabled by default or at what sensitivity though--It might be a little much to have every duplicate flagged by default. It would be interesting to see how many offenses you get on popular / large codebases.

**Comment by backus** [comment]
@dgollahon true. I'll try it on our private codebase and a few others I contribute to see how many false positives there are.

**Comment by andyw8** [comment]
If you can put on a branch, I can try running it on some repos too.

**Comment by backus** [comment]
@andyw8 see #259

**Comment by backus** [comment]
This cop found a few violations in rubocop-rspec that I fixed :)

**Comment by backus** [comment]
I ran this cop on rubocop's specs. I think https://github.com/bbatsov/rubocop/pull/3828 demonstrates that this cop is pretty helpful.

**Comment by backus** [comment]
Implemented in #259
