### ISSUE TITLE
MessageSpies cop

### ISSUE THREAD

**Issue by lucascaton** [backus/rubocop-rspec#268]
Hi there,

There are 2 issues re `MessageSpies` cop (https://github.com/backus/rubocop-rspec/pull/224):

## 1

In the following case, `account` isn't a spy, it's a real object, created by `FactoryGirl`:

```ruby
    let(:error)   { I18n.t 'errors.messages.greater_than_or_equal_to', count: 0 }
    let(:account) { build :account }

    before { expect(account).to receive(:errors).and_return(amount_cents: [error]) }

    # ...
```

Even then, I get this Rubocop message: `RSpec/MessageSpies: Prefer have_received for setting message expectations. Setup account as a spy using allow or instance_spy.`

## 2

`have_received` method doesn't support chaining `and_return` method and I think it should be checked, before failing the code validation:

Error:
```sh
NoMethodError: undefined method `and_return' for #<RSpec::Mocks::Matchers::HaveReceived:0x007fe9ccb409e8>
```

Thank you.

**Comment by backus** [comment]
@bquorning I'll let you handle this

**Comment by bquorning** [comment]
Thanks you for reporting, @lucascaton.

What “MessageSpies” wants you to do here is:

```rb
before { allow(account).to receive(:errors).and_return(amount_cents: [error]) }
```

If you want to keep the expectation, and not just the stubbing, you can add it later in the flow with

```rb
expect(account).to have_received(:errors)
```

The cop is trying to enforce the [Four-Phase Test pattern](https://robots.thoughtbot.com/four-phase-test), where you have the expectations at the bottom of the test (right before teardown).

I agree that we could probably improve the message from the cop. Currently it can easily be interpreted like you should substitute `receive` for `have_received`, which won’t work.

**Comment by lucascaton** [comment]
@bquorning but then, instead of simply:

```ruby
expect(Pusher::Client).to receive(:new).with(
  app_id:    'fake',
  key:       'fake',
  secret:    'fake',
  cluster:   'ap1',
  encrypted: true
).and_return(pusher_client)
```

I'd have to duplicate the code:

```ruby
allow(Pusher::Client).to receive(:new).with(
  app_id:    'fake',
  key:       'fake',
  secret:    'fake',
  cluster:   'ap1',
  encrypted: true
).and_return(pusher_client)

expect(Pusher::Client).to have_received(:new).with(
  app_id:    'fake',
  key:       'fake',
  secret:    'fake',
  cluster:   'ap1',
  encrypted: true
)
```

Or extract the params used in the `with` to a `let`, even though I don't need these in anywhere else.

**Comment by andyw8** [comment]
@lucascaton I think the issue here is because you're mixing together stubbing and expectation for the same method in a single example.

RSpec allows this but rubocop-rspec is trying to discourage it.

I'm not sure I could provide a good clear explanation, so I'd recommend watching this Sandi Metz' talk [The Magic Tricks of Testing](https://www.youtube.com/watch?v=URSWYvyc42M)

And in particular this slide:

![unit-testing-chart-sandi-metz](https://cloud.githubusercontent.com/assets/13400/22005581/825add30-dc32-11e6-86d4-e4a54171ee2d.png)

**Comment by backus** [comment]
@lucascaton I agree with @andyw8 / @bquorning that the point here is to help point out a problematic test. Also though, unless you are also adding message expectations for calls to `Pusher::Client.new` in other cases, you don't have to repeat the `with`:

```ruby
require 'rspec/mocks/standalone'

class Thing
  def self.create(**kw)
  end
end

allow(Thing)
  .to receive(:create)
  .with(foo: 1, bar: 2, baz: 3, qux: 4)
  .and_return(Thing.new)

Thing.create

expect(Thing).to have_received(:create)
```

```sh
$ ruby example.rb
/Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib/rspec/support.rb:87:in `block in <module:Support>': #<Thing (class)> received :create with unexpected arguments (RSpec::Mocks::MockExpectationError)
  expected: ({:foo=>1, :bar=>2, :baz=>3, :qux=>4})
       got: (no args)
Diff:
@@ -1,2 +1,2 @@
-[{:foo=>1, :bar=>2, :baz=>3, :qux=>4}]
+[]

 Please stub a default value first if message might be received with other args as well.
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-support-3.5.0/lib/rspec/support.rb:96:in `notify_failure'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/error_generator.rb:327:in `notify'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/error_generator.rb:311:in `__raise'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/error_generator.rb:63:in `raise_missing_default_stub_error'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:206:in `raise_missing_default_stub_error'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:191:in `message_received'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/proxy.rb:326:in `message_received'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
  from /Users/johnbackus/.gem/ruby/2.3.1/gems/rspec-mocks-3.5.0/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'
  from example.rb:13:in `<main>'
```

**Comment by lucascaton** [comment]
It works and it makes sense. Thanks @backus!
