### ISSUE TITLE
NestedGroups counts levels differently since version 1.9.0

### ISSUE THREAD

**Issue by mvz** [backus/rubocop-rspec#270]
With version 1.8.0, the following does not cause a NestedGroups offense:

```ruby
RSpec.describe Foo do
  context 'bar' do
    it 'baz' do
      pass
    end
  end

  describe '#qux' do
    context 'when quuz' do
      it 'zyxxy' do
        pass
      end
    end
  end
end
```

With 1.9.0, it seems the nested is counted differently, since it registers an offense, even thought the MaxNesting parameter default has stayed the same, at `2`.

This seems to be a bug or regressions, since this changes is not marked in the change log.

**Comment by backus** [comment]
Thanks for the report @mvz I think you're right I'll take a look

**Comment by backus** [comment]
@mvz using your example code I bisected this regression down to bd88c07e7e043b1591210e3b2634ccc47e08a2cc. I'll see if I can fix and push a patch release

**Comment by mvz** [comment]
Thanks, @backus!

**Comment by backus** [comment]
@mvz could you try out #274 before I release it?

**Comment by mvz** [comment]
@backus sure, hold on.

**Comment by backus** [comment]
Thanks :)

**Comment by mvz** [comment]
Looks good, @backus.

**Comment by backus** [comment]
Thanks @mvz
