### ISSUE TITLE
Cop Idea: Replace `instance_double(Foo).as_null_object` with `instance_spy(Foo)` when the double is used with `have_received`

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#275]
Edit: Original idea was to replace all instances of `instance_double(...).as_null_object` with `instance_spy` but I changed my mind in response to the discussion below. Plan now is to replace with spy when the double is used with `have_received`. See discussion below

**Comment by backus** [comment]
thoughts @andyw8 @bquorning ?

**Comment by backus** [comment]
Heh alright maybe it is more controversial than I expected.

I'm actually not sure how to reason about this now. The semantics alone tell me that adding this cop would be fine but I'm not sure how much meaning `double` and `spy` are supposed to actually carry beyond their behavior if that makes sense.

@JonRowe what do you think here? Are there cases where `instance_double(User).as_null_object` should be used instead of `instance_double(User)`?

**Comment by JonRowe** [comment]
> @JonRowe what do you think here? Are there cases where instance_double(User).as_null_object should be used instead of instance_double(User)?

Personally I'd avoid it's use, like the any instance features, but it's a tool for working with legacy code. Spies do something different so I don't feel it's a semantic match...

**Comment by backus** [comment]
Thanks @JonRowe. Are you saying you would avoid the use of `as_null_object`? Also what difference are you referring to for spies? I figured they were equivalent given the code snippet I linked. Do you mean that users are only *supposed* to use spies when using `have_received` like @andyw8 said?

**Comment by JonRowe** [comment]
> Are you saying you would avoid the use of as_null_object?

 Yes

> Do you mean that users are only supposed to use spies when using have_received like @andyw8 said?

Yes, the fact that they use the same code as `as_null_object` is an implementation detail, I'd support converting `as_null_object` calls to `_spy` calls when `have_received` is used tho!

**Comment by backus** [comment]
Neat. Thanks for the input. I'll adjust the scope of this cop idea then to what @andyw8 and you recommended.
