### ISSUE TITLE
Cop Idea: Prefer using the `all` matcher instead of iterating over an array

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#278]
The [`all` matcher](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/all-matcher) is pretty cool. We can't infer a lot of use cases statically of course but I bet we could probably detect enough cases for it to be useful. For example, I've seen some specs like this

```ruby
it 'validates users' do
  [user1, user2, user3].each { |user| expect(user).to be_valid }
end
```

this could be written as

```ruby
it 'validates users' do
  expect([user1, user2, user3].to all(be_valid)
end
```

**Comment by Darhazer** [comment]
I think it should ignore negative expectations.

```
it 'validates users' do
  [user1, user2, user3].each { |user| expect(user).not_to include(1) }
end
```

doesn't look right:
```
it 'validates users' do
  expect([user1, user2, user3]).not_to all { include(1) }
end
```

RSpec [suggest defining negate matchers](https://github.com/rspec/rspec-expectations/issues/658#issuecomment-56762270) in such a case, but I don't think this is something the cop will be able to suggest
