### ISSUE TITLE
Possible need for a new release that doesn't depend on certain changed rubocop internals

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#279]
https://github.com/bbatsov/rubocop/pull/3863 and some other recent refactors might break some of our integration

**Comment by backus** [comment]
This breaks https://github.com/backus/rubocop-rspec/blob/f8e832d1935167619f405d37b02530d792b9be5f/lib/rubocop/cop/rspec/named_subject.rb#L63

**Comment by mikegee** [comment]
#281 closes this issue, right?

**Comment by backus** [comment]
Ah correct thanks @mikegee
