### ISSUE TITLE
Suggestion: Rspec/NestedGroups maximum option

### ISSUE THREAD

**Issue by MadhuriShres** [backus/rubocop-rspec#286]
This is just a suggestion from my part since I got a bit confused while trying to set custom maximum value for nested groups example.

The maximum value set for most of the cops use key `Max` but for `NestedGroups` it is `MaxNesting`.
https://github.com/backus/rubocop-rspec/blob/master/config/default.yml#L130

Perhaps I might be wrong or I might be too late to suggest but I think it would be a consistent behaviour among cops if we can use just `Max` as key to set maximum values. Thanks for your time and efforts. 🙇

**Comment by backus** [comment]
Yeah I should make that consistent in the next version. Thanks for the input!

**Comment by MadhuriShres** [comment]
Thank you for such a quick and positive response. Since you have labelled it as a bug, should I submit a PR with the change?

**Comment by backus** [comment]
I was about to actually. To do this properly I think I need to add a check to the config that warns about `MaxNesting` but still respects it. That is a more involved change so it might be easier for me to do it.

If you're interested in helping though [there are plenty of cops](https://github.com/backus/rubocop-rspec/issues?q=is%3Aissue+is%3Aopen+label%3Acop) that can be implemented. I think these are way more fun to work on too.

**Comment by MadhuriShres** [comment]
Sounds great! Thank you once again 🙇

**Comment by backus** [comment]
#287 should fix this issue. Not sure when we'll release it FYI. Thanks again for the feedback
