### ISSUE TITLE
Recommend shared_examples or shared_context instead depending on contents

### ISSUE THREAD

**Issue by backus** [backus/rubocop-rspec#293]
I think a nice cop would be something that enforces the following

```ruby
# This should be `shared_examples` since it only defines examples
RSpec.shared_context 'only examples here' do
  it 'does x' do
  end

  it 'does y' do
  end
end

# This should be `shared_context` since it only does setup
RSpec.shared_examples 'only setup here' do
  subject(:blah) { hello }

  let(:foo) { bar }

  before do
    blah
  end
end
```

If setup and examples are both defined inside the definition then the cop should ignore it. Same if it uses any rspec keywords that might include other behavior. Same if it does `include_examples` or `include_context`.

**Comment by backus** [comment]
@bquorning @andyw8 any thoughts here?

**Comment by dgollahon** [comment]
@backus: I like this one. I think it's definitely nice to use the most descriptive name.

**Comment by backus** [comment]
Cool. @bquorning @andyw8 I'm marking this as a cop for now (meaning I think it is valid to implement and release).

@JonRowe since this is another assumption about intended RSpec conventions would you like to weigh in here? (Also, are you cool with me continuing to occasionally ping you for your opinion on various rubocop-rspec decisions 😅?)

**Comment by JonRowe** [comment]
Theres no convention I know of here, but seems fine :)
