### ISSUE TITLE
Conflict between Rails/FilePath and RSpec/FilePath

### ISSUE THREAD

**Issue by bquorning** [backus/rubocop-rspec#299]
I haven’t debugged this at all, but it seems that a config entry for RSpec/FilePath is read by RuboCop v0.47.0 as config for the new Rails/FilePath cop. Are namespaces ignored by “master” RuboCop?

I’m using rubocop v0.47.0 and rubocop-rspec v1.10.0.

**Comment by backus** [comment]
Damn I thought I helped fix this. Thanks for reporting

**Comment by backus** [comment]
Solution in the pipeline. See all the commit noise above :laughing:

**Comment by bquorning** [comment]
Sorry, your fix doesn’t resolve my issue. I’ll try to come up with a minimal reproducible example.

**Comment by bquorning** [comment]
Sorry for the false alarm. Your fix works splendidly!

**Comment by erikogan** [comment]
I have a project pulling its configuration from a gem that is exhibiting this issue. I’ll try to put together a simple reproduction case to tease apart what is happening. I’ll post it to the backus/rubocop issue once I have it.

**Comment by backus** [comment]
@erikogan make sure to include your rubocop and rubocop-rspec versions. basically, if rubocop-rspec isn't required before `RSpec/FilePath` is referenced then it will cause a warning and undesired behavior. I think there are still edge cases where it still happens but most primary cases are fixed i think. partially an issue of rubocop-rspec being an unofficial extension

**Comment by Epigene** [comment]
I'm still getting this on `v0.61.1`. When running `rubocop --only "RSpec/FilePath"` rubocop runs as if I'd specified `rubocop --only "Rails/FilePath"`.

My config is this:

```yml
Rails/FilePath:
  Enabled: false

RSpec/FilePath: 
  Enabled: true
```

Interestingly, when i simply run `rubocop`, the check is correct.
