### ISSUE TITLE
Add Cop to require aggregate_failures

### ISSUE THREAD

**Issue by thegranddesign** [backus/rubocop-rspec#312]
Related to https://github.com/backus/rubocop-rspec/issues/233

It would be nice to have a cop that required multiple expectations to be wrapped in `aggregate_failures`.  I know I forget to do this all the time.

**Comment by backus** [comment]
I think the best bet for that might be #233. It seems impossible to tell whether people are making one business rule level assertion (and should use `aggregate_failures`) or if they are making multiple (and should split their example into multiple separate examples).

**Comment by thegranddesign** [comment]
Which is what `rubocop:disable` is for. If I, as a developer, always want aggregate failures, then that is my choice. 

However, I reached out to the RSpec team and there is this:

**Comment by backus** [comment]
Interesting! Well I'll think about that cop. Personally I still usually want to check whether team mates should be using `aggregate_failures` or not but I could also see wanting to just blanket apply it
