### ISSUE TITLE
Described class cop with SkipBlocks disabled is kind of useless

### ISSUE THREAD

**Issue by redross** [backus/rubocop-rspec#318]
Maybe I'm missing something, but it seems that if SkipBlocks is not disabled this cop will complain about cases where it's impossible to fix it. What's even more strange, it seems that the test suite includes such case as an example ([here](https://github.com/backus/rubocop-rspec/blob/c4c80620416405dd78f418ca9c32b980b7c3a39a/spec/rubocop/cop/rspec/described_class_spec.rb#L33..L36))

Cases where some module needs to be tested (rails concerns?) seem to be quite common:
```ruby
RSpec.describe Something::UserValidation do
  controller do
    include Something::UserValidation
    
    def smth
     render :ok
    end
  end
#...
```

and even though it would complain about changing the `Something::UserValidation` to `described_class`, that cannot be done since the context is changed in the `controller` block.

The cop already includes some checks for context changes ([here](https://github.com/backus/rubocop-rspec/blob/c4c80620416405dd78f418ca9c32b980b7c3a39a/lib/rubocop/cop/rspec/described_class.rb#L49)), but I guess it needs to be improved and/or made configurable?

**Comment by backus** [comment]
By the way, if you're interested in specific handling of rspec-rails DSL I'm happy to take a PR for that. I don't work with rails much so it never really reaches high enough on my priority list to implement it for others

**Comment by redross** [comment]
Hmm, disabling this only for some directory seems like a great idea.

I just started trying out the how the gem works internally but will try to make this more configurable. Thanks for the quick response.

**Comment by backus** [comment]
Seems like this resolved the issue? I'll close for now. Let me know if you are still looking for some change in rubocop-rspec for this @redross
