### ISSUE TITLE
Cop suggestion: Indirect call to subject

### ISSUE THREAD

**Issue by andyw8** [backus/rubocop-rspec#320]
I recently came across Rails model spec which at no point references the model being tested, either by its class name, or by `subject`. Instead, it calls a different model, which then calls the model the spec is targeting. I don't know what to call it (`IndirectSubject`?) but I think this would be a useful smell to warn about.

(Hope this is clear, if not, I can add an example)

**Comment by backus** [comment]
An example would be great. AFAICT from your description, this sounds out of scope of static analysis, but maybe I am misunderstanding.

**Comment by andyw8** [comment]
My description above isn't quite right, but here's what I mean:

```ruby
describe Foo do
  specify do
    expect { Bar.call }.to change { Foo.count }.by(1)
  end
end
```

**Comment by backus** [comment]
Ah interesting. It would be nice to get some more examples here. This `expect { ... }.to change` example seems like a reasonable thing to flag. I'm wondering what else falls in this category though.

**Comment by andyw8** [comment]
Yeah, maybe it's difficult to generalise. I'll close this for now and come back it if I come across a similar case.
