### ISSUE TITLE
Detect specs missing a `_spec` ending in filename

### ISSUE THREAD

**Issue by andyw8** [backus/rubocop-rspec#324]
I discovered some specs in a test suite which were not being executed in CI because they didn't end in `_spec.rb`.

I thought the `RSpec/FilePath` would have caught this, but these files were ignored because they are excluded by the filter:

https://github.com/backus/rubocop-rspec/blob/master/config/default.yml#L5

Any thoughts on how this could be handled? I imagine it would need to ignore `spec/support/*.rb`, `spec_helper.rb`, etc.

**Comment by backus** [comment]
It is a bit tricky since ignoring non spec files means that rubocop-rspec doesn't waste half of its time scanning irrelevant source files. We can probably override this though for `FilePath`

**Comment by backus** [comment]
@andyw8 I have a fix open on #331 if you would like to take a look

**Comment by andyw8** [comment]
@backus thanks for adding!
