### ISSUE TITLE
Detecting overriding same let in same rspec scope

### ISSUE THREAD

**Issue by Dorian** [backus/rubocop-rspec#328]
Avoid copy-paste / grammar errors by detecting overriding same rspec `let` / `let!` / `subject`, e.g.

```ruby
let(:a1) { 1 }
let(:a1) { 2 }
```

--------

## Expected behavior

This should create an offense:

```ruby
let(:a1) { 1 }
let(:a1) { 2 }
```

Correct code could be:

```ruby
let(:a1) { 1 }
let(:a2) { 2 }
```

## Actual behavior

It doesn't create an offense

## RuboCop version

```
0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

(mostly just a memo for myself to create this cop, originally filed there: https://github.com/bbatsov/rubocop/issues/4057)

**Comment by backus** [comment]
I'd accept a cop for this. Also note that you can catch this in the meantime with by running `rspec --warnings`

**Comment by Dorian** [comment]
@backus Oh thanks :) (`--warnings` produce 1420 lines in my case :) )

```
warning: method redefined; discarding old a1
warning: previous definition of a1 was here
warning: method redefined; discarding old a1
warning: previous definition of a1 was here
```

**Comment by Darhazer** [comment]
I would add detecting of let overwritting by a var in the example:

```
let(:a1) { 1 }

it 'is not used'
  a1 = 2
end
```

Not sure if it has to be the same cop

**Comment by bquorning** [comment]
> Correct code could be:
> ```rb
> let(:a1) { 1 }
> let(:a2) { 2 }
> ```

That would lead to `a2` being an unused `let`. I’d say the correct code should be
```rb
let(:a1) { 2 }
```
