### ISSUE TITLE
Could you add a bit more in readme

### ISSUE THREAD

**Issue by gamesover** [backus/rubocop-rspec#372]
I have a bit doubts about this project, such as:
1. do I still need `rubocop` gem to check the rest of project except `spec` folder?
2. how this gem work with `rubocop` gem? If I want to check normal code + test code(`spec` folder), shall I install both gems and run as simple as `rubocop` or shall I do something else?

Hopefully, those info could be added into `readme`, thanks.

**Comment by Darhazer** [comment]
1. You need rubocop to use rubocop-rspec. Since rubocop is dependency of rubocop-rspec, it will be installed anyway.

2. It's described under `Usage`
> You need to tell RuboCop to load the RSpec extension. There are three ways to do this:

**Comment by bquorning** [comment]
@gamesover I’m gonna close this issue, but feel free to reopen (or better yet, open a PR) if you still feel the README needs improvement.
