### ISSUE TITLE
Cop idea: ActiveRecord bang methods

### ISSUE THREAD

**Issue by Dorian** [backus/rubocop-rspec#377]
`it  { expect { user.update(name: nil) }.to ...` could fail silently, so `it  { expect { user.update!(name: nil) }.to ...` is preferred.

This would apply for most ActiveRecord bang methods, e.g.:

- `save!`
- `update!`
- `destroy!`
- `create!`
- etc.

**Comment by andyw8** [comment]
Note that there's already a cop in RuboCop itself for `save!`:

https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/rails/save_bang.rb

**Comment by backus** [comment]
Yeah I think this is a better suited to rubocop itself. We don't really have a rails specific config for rubocop-rspec and these methods are also pretty generic so it seems like not a great fit for rubocop-rspec. Interesting idea though @Dorian.

**Comment by Dorian** [comment]
Nice, thanks a lot @andyw8 !!! Detecting if the return value is used is so much smarter!
