### ISSUE TITLE
Cop Idea: Forbid non static sentences declared statically on factories

### ISSUE THREAD

**Issue by jonatas** [backus/rubocop-rspec#393]
Hi, I'm going to work in a cop for factories (using factory girl), complaining against nonstatic attributes declared statically.

The idea is cover cases like:

```ruby
# bad
kind [:active, :rejected].sample
# good
kind { [:active, :rejected].sample }

# bad
closed_at 1.day.from_now
# good
closed_at { 1.day.from_now }

# good
kind :static

# good
comments_count 0

# good
type User::MAGIC
```

Maybe the `rubocop-rspec` project is a good place to put this Cop. Are you interested in receiving a contribution with a Cop like this?

**Comment by Darhazer** [comment]
I'm planning on implementing some rails and capybara specific cops, so FactoryGirl extension is also welcome. I think however that all those not-core extensions have to be in their own namespaces (`RSpec/FactoryGirl/....`) and to have global on/off switch, e.g. disabling all factorygirl checks at once
