### ISSUE TITLE
Cop: RSpec/DescribeClass and nested request specs

### ISSUE THREAD

**Issue by FQ400** [backus/rubocop-rspec#397]
Hey,

thank you for this nice collection of cops. 👍 
I have anunexpected behaviour regarding the `RSpec/DescribeClass` cop.

```
spec/requests/api/v0/signed_requests_spec.rb:3:16: C: RSpec/DescribeClass: The first argument to describe should be the class or module being tested.
RSpec.describe 'Signed Requests' do
               ^^^^^^^^^^^^^^^^^
```

My directory structure in `spec/requests/*_spec.rb` and `spec/requests/api/v0/*_spec.rb`.

All files in `spec/requests/*_spec.rb` do not show the the warning and have describe blocks like: `RSpec.describe 'Preferences' do` or `RSpec.describe 'Campaigns' do`

When I move the nested file into `spec/requests/` then the warning is gone.

I use the rubocop version `0.48.1` and rubocop-rspec version `1.15.0`

What do you think?

**Comment by backus** [comment]
Code like `RSpec.describe 'Preferences' do` is probably not being flagged because the contents of the string is a valid constant. I think we have had other issues mentioning this. Try adding a directory ignore to your config file for `spec/requests` for this cop.

**Comment by FQ400** [comment]
Ah. 😄  Thanks for the hint. My rubocop rule now looks like:
```
RSpec/DescribeClass:
  Exclude:
    - spec/features/*
    - spec/requests/**/*
```

**Comment by backus** [comment]
Very nice. I have something similar in my projects:

```
RSpec/DescribeClass:
  Exclude:
  # In integration tests we want to describe a route not a class
  - spec/integration/requests/**/*.rb
```
