### ISSUE TITLE
Allow rake task descriptions in describe_class

### ISSUE THREAD

**Issue by npetkov** [backus/rubocop-rspec#399]
Currently, describing a task via `describe 'namespace:task'` will generate a warning. It'd be nice to allow `type: :rake` or similar metadata in order to reduce noise when testing rake tasks (yes, some people do that).

**Comment by backus** [comment]
Have you considered disabling the cop for whatever your `spec/rake` directory is?

Also I test my rake tasks too heh. I actually just extract the code to some callable object though so I don't have to go through the madness of like `Rake.application['my_task'].invoke!` or whatever. Rake should just be a thin wrapper

**Comment by npetkov** [comment]
I ended up just ignoring the whole tasks dir, maybe it really isn't worth the time and trouble. Thanks for the fast response.
