### ISSUE TITLE
Auto correct of RSpec/ExampleWording crashes

### ISSUE THREAD

**Issue by phansch** [backus/rubocop-rspec#402]
Hello! I have been using rubocop-rspec without any issues so far and like it a lot. However, today I started to use it on a bigger project and I found the following example that crashes the auto correct:

```ruby
# model_spec.rb
it 'It does something' do
  # ^ Note the uppercase i
end
```

If I run it without the autocorrect, the offense is registered correctly:

```
$ rubocop --only RSpec/ExampleWording model_spec.rb 
Inspecting 1 file
C

Offenses:

model_spec.rb:1:5: C: Do not repeat 'it' when describing your tests.
it 'It does something' do
    ^^^^^^^^^^^^^^^^^
```

However, it breaks with the `--auto-correct` flag:

```
$ rubocop --only RSpec/ExampleWording --auto-correct model_spec.rb
Inspecting 1 file


0 files inspected, no offenses detected
no implicit conversion of nil into String
/home/phansch/.rvm/gems/ruby-2.3.1/gems/parser-2.3.3.1/lib/parser/source/rewriter.rb:156:in `[]='
/home/phansch/.rvm/gems/ruby-2.3.1/gems/parser-2.3.3.1/lib/parser/source/rewriter.rb:156:in `block in process'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/parser-2.3.3.1/lib/parser/source/rewriter.rb:152:in `each'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/parser-2.3.3.1/lib/parser/source/rewriter.rb:152:in `process'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/corrector.rb:63:in `rewrite'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:143:in `autocorrect_all_cops'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:80:in `autocorrect'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:108:in `block in offenses'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:125:in `investigate'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:104:in `offenses'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/cop/team.rb:54:in `inspect_file'
/home/phansch/.rvm/gems/ruby-2.3.1/gems/rubocop-0.48.1/lib/rubocop/runner.rb:248:in `inspect_file'

```

I guess that's because [`replacement_text`](https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/example_wording.rb#L77) returns `nil` in that case. I probably have time to look into a fix later today.

**Comment by bquorning** [comment]
That cop has a few inconsistencies:

- `if text.start_with?('should')` should use `SHOULD_PREFIX` instead.
- `#on_block` downcases the message, which `#replacement_text` doesn’t do, which causes the error you’re seeing.
- `IT_PREFIX` includes a whitespace, but `SHOULD_PREFIX` doesn’t.

**Comment by dgollahon** [comment]
Thanks for the report, @phansch! I added the `it` functionality so I'm happy to fix the bug after work tonight. If you prefer to submit a patch before tonight, that's fine too!

@bquorning:
> IT_PREFIX includes a whitespace, but SHOULD_PREFIX doesn’t.

iirc, this is necessary for some cases of `shouldn't` or similar words that include should. I deliberately included the space for the `it` since I only care about exactly that word followed by a space.

**Comment by dgollahon** [comment]
Slightly o/t, but this cop is a good argument for #232 or something kind of like it. I realized after implementing the repeated it behavior that it's a shame that the offenses can't easily be independently flagged or corrected. They do both belong to the idea of "example wording" though, so it didn't feel right to have a separate cop either.

**Comment by phansch** [comment]
@dgollahon I won't have more time for this unfortunately and I see you already have a PR open. Thanks for the quick response :tada:
