### ISSUE TITLE
FileName cop to check rspec file ends in _rspec

### ISSUE THREAD

**Issue by IanVaughan** [backus/rubocop-rspec#412]
We just hit this, and thought maybe it should be added to the core...

Similar to [file_name.rb] in Rubocop core, the idea here would be to check files under the `/spec` directory to ensure they end in `_rspec`.

Users would need to exclude common non-spec directories like fixtures etc, and maybe this could provide a suggested default for common ones?

I'm happy to do this myself, but just wanted to check if a) I had missed this if already present, or b) was going in the wrong direction and should think of something else!

```
# @example
    #   # bad
    #   whatever.rb 
    #
    #   # bad
    #   whatever_foo.rb 
    #
    #   # good
    #   whatever_spec.rb 
```

See also [file_path.rb]

[file_name.rb]:https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/file_name.rb
[file_path.rb]:https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/file_path.rb

**Comment by andyw8** [comment]
I think you meant to write "check rspec file ends in _spec"?

The `RSpec/FilePath` cop already handles this, for example if you create a file `spec/foo.rb` containing a `describe` block, it will report:

```
spec/foo.rb:1:1: C: Spec path should end with foo*_spec.rb.`
describe Foo do
^^^^^^^^^^^^
```
