### ISSUE TITLE
Cop idea: disallow eq for arrays

### ISSUE THREAD

**Issue by Darhazer** [backus/rubocop-rspec#424]
Most time people use `expect(arr).to eq [1,2,3]` they don't really care about the order. In such cases `contain_exactly` and `match_array` will make for better tests, as checking the exact order of elements can lead to flaky tests. If one wants to check the order of the elements as well, he have to be explicit about it.

**Comment by bquorning** [comment]
>  If one wants to check the order of the elements as well, he have to be explicit about it.

How would he do that, without using `eq`?

**Comment by Darhazer** [comment]
By disabling the cop ;)

Or by using `to be == b`, or `to satisfy`. I really don't answer actually, in my codebase I left the `eq` matcher in the cases where the description of the test says it expect specific order, and replaced with match_array the rest.

So such a cop is maybe too opinionated and if it's ever made should be disabled by default, but my experience is that `eq` is over-used for arrays, when people really want a `match_array`

**Comment by bquorning** [comment]
> So such a cop is maybe too opinionated

Yeah. I don’t like cops that disallow using potentially confusing, but perfectly valid constructs. For example, I always disable `Style/AndOr` and `Style/DoubleNegation` – I *know* the difference between `&&` and `and`, `||` and `or`, and I know what `!!` means, and I (like to believe I) know what I’m doing when choosing either of those.
