### ISSUE TITLE
Allow RSpec/FilePath pass on nested folder

### ISSUE THREAD

**Issue by wbotelhos** [backus/rubocop-rspec#429]
Hi, Congrats for you great work on this gem.

I would like to suggest the Cop `RSpec/FilePath` allow this pattern that a used to do.

For:

```ruby
admin/plans_controller.rb
```

I separate the classes by folder, to avoid a lot of files in the same level:

```ruby
spec/controllers/admin/plans/create_spec.rb
```

But the Cops wants:

```ruby
spec/controllers/admin/plans_controller_create_spec.rb
```

1. Maybe `_controller` is redundant since this file is already inside the folder `controllers`;
2. Options to swap the prefix `plans_` to a folder `plans` will give more flexibility on a new namespace.

For big projects, separares the controllers folder is a hand to keep the things organized.

Thank you! (:

**Comment by bquorning** [comment]
According to the specs, both forms are allowed: https://github.com/backus/rubocop-rspec/blob/3e6c4277ae1b4465578660de4fa3a51e6ab4a85f/spec/rubocop/cop/rspec/file_path_spec.rb#L109-L131

You would probably need to rename the folder so you have `spec/controllers/admin/plans_controller/create_spec.rb` instead of `spec/controllers/admin/plans/create_spec.rb`.

**Comment by wbotelhos** [comment]
Hi @bquorning , thank you for your answer.
Any change to have some options to avoid repeat the name `_controller` on folder, since we already inside the `spec/controllers` folder? Like: `prefix: false`

Thanks.

**Comment by bquorning** [comment]
I think it’s fair that the file name matches the name of the class under test – e.g. for `PlansController` you have `plans_controller_spec.rb` or `plans_controller/create_spec.rb`.

Another option (not a recommendation, just an observation): I don’t think Rails forces you to end your controller names with `Controller`. That said, it’s probably healthy from a namespace point of view (if you happen to also have a `Plans` model)..

**Comment by wbotelhos** [comment]
No problem, it was just a suggestion.
I'll keep avoiding to repeate `_controller` inside the folder controller.

Thanks for this great gem. (:
