### ISSUE TITLE
Test is failed with RuboCop HEAD

### ISSUE THREAD

**Issue by pocke** [backus/rubocop-rspec#435]
A method signature of `autocorrect_source` has been changed  by https://github.com/bbatsov/rubocop/pull/4510 .
So the test for rubocop-rspec is failed with next version RuboCop.

This problem can be avoided by one of the following methods.

1. Drop rubocop 0.49.1 or older support if rubocop 0.50.0 is released
1. Pin rubocop version with 0.49.1 or older
1. Check `Method#arity` for `autocrrect_source` method.
  - This way supports both rubocop versions, but it's a workaround.

**Comment by backus** [comment]
Nice. I just noticed while working on a rubocop PR that a few things are failing on the latest master. What I usually do is just make then new release be constrained to the latest rubocop release. Easiest that way.
