### ISSUE TITLE
Detect aggregate_failures set via metadata

### ISSUE THREAD

**Issue by AlexVPopov** [backus/rubocop-rspec#451]
Hello,

I have enabled `aggregate_failures` [globally](https://relishapp.com/rspec/rspec-core/docs/expectation-framework-integration/aggregating-failures#enable-failure-aggregation-globally-using-`define-derived-metadata`):
```ruby
config.define_derived_metadata { |meta| meta[:aggregate_failures] = true }
```
I still get violations from `RSpec/MultipleExpectations`. Is this the expected behavior? What is the solution/workaround - should I just turn off the cop?

**Comment by Darhazer** [comment]
As this is static analysis tool, I don't think we can catch such global configuration. In this case you can safely disable the cop, as you will always have just one aggregate_failures block per example (unless you override with `aggregate_failures: false` in some example.

**Comment by AlexVPopov** [comment]
Thank you :)
