### ISSUE TITLE
LetBeforeExamples when using a let block within it_behaves_like block

### ISSUE THREAD

**Issue by viamin** [backus/rubocop-rspec#456]
I'm seeing LetBeforeExamples offenses after upgrading to rubocop-rspec 1.16.0 (from 1.15.1)

```
RSpec.describe Model, type: :model do
  it_behaves_like 'shared_example' do
    let(:model_variable) { 'some variable specific to this model' }
  end
end
```
results in:
`RSpec/LetBeforeExamples: Move let before the examples in the group.`

Similar to https://github.com/backus/rubocop-rspec/issues/454

**Comment by bquorning** [comment]
Yeah, I've seen this issue too.
