### ISSUE TITLE
Cop idea: force gem versions in Gemfile

### ISSUE THREAD

**Issue by alebian** [backus/rubocop-rspec#467]
Hi!

Many times I've seen problems when some gem, without noticing, gets updated to a newer version. I believe that versioning the gems in our Gemfile is a very good practice and we could have a Cop that enforces this.

I've created a prototype for this [here](https://gist.github.com/alebian/9a980f514001ae62b46d5469e5bb92c8).

Let me know what you think about it and if you think this deserves a PR or maybe create an extension gem.

Thanks!

**Comment by backus** [comment]
Hey @alebian this probably belongs to rubocop itself. You should submit an issue to https://github.com/bbatsov/rubocop. Thanks!

**Comment by alebian** [comment]
@backus OMG you are right... I was looking at your code for examples and I created the issue in the wrong repo 😅 fail!
