### ISSUE TITLE
Do not raise RSpec/MultipleExpectations when using "ordered" message matchers

### ISSUE THREAD

**Issue by Richard-Degenne** [backus/rubocop-rspec#478]
When you need to test for the order of certain messages, rspec has the [`ordered`](https://relishapp.com/rspec/rspec-mocks/v/3-2/docs/setting-constraints/message-order) matcher modifier.

However, using this feature kinda forces you to have multiple expectations in a single test case, which triggers the `RSpec/MultipleExpectations` cop.

Is it possible to make this cop aware of this case? Disabling it around the case kinda feels like a work-around, to be honest.

I'll add an example when I have some time and if the issue proves interesting.

**Comment by Darhazer** [comment]
You can mark the example with `aggregate_failures` instead of disabling the cop - if this workaround seems better to you.

As for the `ordered`, I hesitate to handle it in the cop, as using ordered is not a recommended anyway. 

> This is not generally recommended because in most situations the order doesn't matter and using
> ordered would make your spec brittle,

**Comment by Richard-Degenne** [comment]
Yeah, that's what I thought.

Also, I didn't know about the aggregate failure, thanks for pointing it out!
