### ISSUE TITLE
ImplicitExpect should also prefer `not_to` over `to_not`.

### ISSUE THREAD

**Issue by reitermarkus** [backus/rubocop-rspec#480]
When only running the `RSpec/ImplicitExpect` cop, it auto-corrects `should_not` to `is_expected.to_not` instead of `is_expected.not_to`. It should instead prefer `not_to`, like the `RSpec/NotToNot` cop.

**Comment by bquorning** [comment]
Auto-correction using a subset of your enabled cops may sometimes generate output that doesn’t satisfy some of the disabled cops. I would generally recommend only using auto-correct *without* the `--only` option.
