### ISSUE TITLE
Add rubocop-rspec

### ISSUE THREAD

**Issue by sauloperez** [backus/rubocop-rspec#501]
## What?

Now that we finally got to RSpec 3, it's time to add https://github.com/backus/rubocop-rspec to our Rubocop to enforce a style guide also for our test suite. This will also make the transition to RSpec 3 syntax and additions easier.

**Comment by Darhazer** [comment]
@sauloperez maybe you have opened this issue in the wrong repo?

**Comment by sauloperez** [comment]
Oops! wrong tab! My apologies @Darhazer
