### ISSUE TITLE
RSpec/DescribeClass false positive

### ISSUE THREAD

**Issue by fedeest** [backus/rubocop-rspec#504]
## Problem description
On each of my spec files I get the following error (as an example):

```
spec/controllers/loans_controller_spec.rb:3:10: C: RSpec/DescribeClass: The first argument to describe should be the class or module being tested.
describe LoansController do
         ^^^^^^^^^^^^^^^
```

As you can see, the class name is fine. The same happens for all the spec files and corresponding classes on my spec folder.

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.3.4 x86_64-linux)
```

**Comment by bquorning** [comment]
> The same happens for all the spec files and corresponding classes on my spec folder.

Just in spec/controllers/, or in all of spec/?

Which version of rubocop-RSpec do you use?

**Comment by fedeest** [comment]
In all specs (I currently only have Controller and Model specs).

I was using rubocop-rspec 1.10. Upon realization of this, I updated the version to 1.20.1 and it no longer showed that error.

I'll close the issue since the problem has been resolved updating the version.
