### ISSUE TITLE
Cop idea: it without description

### ISSUE THREAD

**Issue by Darhazer** [backus/rubocop-rspec#516]
RSpec allows for auto-generated descriptions, based on the expectation used. I personally don't like this style. But even if used, I've seen people put an empty string as description, instead of omitting it completely. So I propose cop that detect this and removes the empty string, as well as having an option to completely disable usage of it without a description

**Comment by dgollahon** [comment]
Agreed. I've been thinking about adding this for a while but haven't gotten around to it.
