### ISSUE TITLE
[Cop idea] ADD cop that check have_http_status value

### ISSUE THREAD

**Issue by anthony-robin** [backus/rubocop-rspec#544]
There is two ways to check the http status of a request with rspec: with the numeric or with symbol value.

```ruby
it { is_expected.to have_http_status :ok }
it { is_expected.to have_http_status 200 }
```

That could be a good cop idea to force the way to check status and set to numeric or symbol value ! What do you think about this ?

**Comment by bquorning** [comment]
Generally, I think it sounds like a good idea. Just a few quick comments:

- This is an rspec-rails specific feature, right?
- Using symbols, you can match “general response codes” (one of `:error`, `:success`, `:missing`, and `:redirect`) which will match an entire class of other symbols, e.g.  `expect(response).to have_http_status(:error)` will match a `:bad_gateway` response – see https://relishapp.com/rspec/rspec-rails/docs/matchers/have-http-status-matcher#checking-a-general-response-code

Would you be interested in implementing such a cop?

**Comment by anthony-robin** [comment]
> This is an rspec-rails specific feature, right?
Yes I think so.

> Would you be interested in implementing such a cop?
I would try to work on this cop this week but I'm not sure my Ruby skills are strong enough to achieve it :(
