### ISSUE TITLE
FactoryBot/DynamicAttributeDefinedStatically does handle dynamic values in arrays/hashes

### ISSUE THREAD

**Issue by abrom** [backus/rubocop-rspec#555]
Neither of the following cases are detected as being dynamic factory girl values
```
foo [Time.current]
foo(bar: Time.current)
```

I tried having a go at fixing it by iterating over the attribute values but it ends up marking the trait tests as an offence (if a child has an offence):

```
def_node_search :dynamic_calls, <<-PATTERN
(send ...)
PATTERN

def_node_search :attribute_values, <<-PATTERN
(send nil? _ $...)
PATTERN

def_node_search :factory_attributes, <<-PATTERN
(block (send nil? {:factory :trait} ...) _ { (begin $...) $(send ...) } )
PATTERN

def on_block(node)
  return if node.method_name == :trait
  factory_attributes(node).to_a.flatten.each do |attribute|
    attribute_values(attribute).to_a.flatten.each do |value|
      next if dynamic_calls(value).to_a.none?
      add_offense(attribute, location: :expression)
    end
  end
end
```

fails the trait spec with:

```
        factory :post do
          title "Something"
          trait :published do
+         ^^^^^^^^^^^^^^^^^^^ Use a block to set a dynamic value to an attribute.
            published_at 1.day.from_now
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use a block to set a dynamic value to an attribute.
          end
```

I suspect the fix might be to check if the `attribute` root node is a trait, and if so, get the child and add the offence to that? Thoughts?

**Comment by Darhazer** [comment]
The fix would be to capture the argument and to check if it's `recursive_literal` - see `ReturnFromStub` cop

**Comment by abrom** [comment]
Great, thanks @Darhazer! I've created #556 which uses your suggestion. Appears to work as expected now. Note I also had to check `const_type?` as they aren't identified with `recursive_literal?`

See https://github.com/backus/rubocop-rspec/pull/556/files#diff-df9ebb129542f128b1ad39adc760d858R46
